import "@/styles/globals.css";

import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import MainFooter from "@/components/MainFooter";
import ReduxContainer from "@/redux/ReduxContainer";
import NavbarSub from "@/components/NavbarSub";
import { Toaster } from "react-hot-toast";

const Gilroy = localFont({
  src: [
    {
      path: "./fonts/Gilroy-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-Thin.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/Gilroy-UltraLight.ttf",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-Gilroy",
});

export const metadata = {
  title: "E-learn",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className={Gilroy.variable}>
      <body className="min-h-screen flex flex-col">
        <ReduxContainer>
          <Toaster />
          <Navbar />
          {children}
          <MainFooter />
        </ReduxContainer>
      </body>
    </html>
  );
}
